### ISSUE TITLE
Office Profile build - Hours Available auto populating

### ISSUE THREAD

**Issue by rchristenson** [topcoderinc/mjolnir-web#1]
I don't know if its possible but on the app version, once you pick the start and end time in the app it auto populates the remaining work days with the same selection. This just makes it easy for the user signing up.

![image](https://user-images.githubusercontent.com/31657407/34876971-02b35f38-f772-11e7-9d76-1df05ba9f6ee.png)

**Comment by mahestro** [comment]
Fixed.
