### ISSUE TITLE
Landing page doesn’t look right or good. Help Mahestro

### ISSUE THREAD

**Issue by bckingsbury** [topcoderinc/mjolnir-web#102]
### OS and Browser Details ###
*Ipad Pro - 11.2.6

### Screen Name where the issue occurs ###
*Landing page
### Exact Reproduction Steps ###
1. Go to the landing page
2. 

### Actual  Result ###
See attached

### Expected Result ###
See attached
![60d745da-afcb-4756-994e-051c01aad9e4](https://user-images.githubusercontent.com/31655780/36693712-2bdd77fc-1b0a-11e8-9466-25f5e023df29.jpeg)

### Screenshots/Video ###
*Paste screenshots here. For video, compress and attach*

**Comment by mahestro** [comment]
Dup #99
