### ISSUE TITLE
Notifications pop up buttons don’t work

### ISSUE THREAD

**Issue by bckingsbury** [topcoderinc/mjolnir-web#104]
### OS and Browser Details ###
*iPad Pro - 11.2.6
### Screen Name where the issue occurs ###
*The Profiles screen when first loging back into the app
### Exact Reproduction Steps ###
1. Login and then the pop ups appear on the profiles page, which is the first page you are taken to
2. 

### Actual  Result ###
See attached

### Expected Result ###
See atached
![276c96d7-8806-4904-86bd-f7ba70352825](https://user-images.githubusercontent.com/31655780/36693992-e8045be4-1b0a-11e8-83e1-3645e6882066.jpeg)

### Screenshots/Video ###
*Paste screenshots here. For video, compress and attach*

**Comment by mahestro** [comment]
Duplicate #110
