### ISSUE TITLE
Changes need to made to the “You’ve got a request to match” pop up notification

### ISSUE THREAD

**Issue by bckingsbury** [topcoderinc/mjolnir-web#106]
### OS and Browser Details ###
*iPad pro - 11.2.6

### Screen Name where the issue occurs ###
*profiles page when first logging in. 

### Exact Reproduction Steps ###
1. Login and its one of the notifications that appear on the profile page. 
2. 

### Actual  Result ###
See attachment

### Expected Result ###
See attachement

### Screenshots/Video ###
*Paste screenshots here. For video, compress and attach*
![63039931-9eb3-4426-bf5e-7c8e6a0f5024](https://user-images.githubusercontent.com/31655780/36694194-974c67ea-1b0b-11e8-94ef-510cc626c8c2.jpeg)

**Comment by mahestro** [comment]
Duplicate #104
