### ISSUE TITLE
The edit benches button doesn’t work

### ISSUE THREAD

**Issue by bckingsbury** [topcoderinc/mjolnir-web#109]
### OS and Browser Details ###
*ipad Pro - 11.2.6
### Screen Name where the issue occurs ###
*Benches section, inside of a selected bench. 
### Exact Reproduction Steps ###
1. Click the edit button when inside of a selected bench
2. 

### Actual  Result ###
See attached

### Expected Result ###
See attached
![276026b6-fbc0-41a1-904a-b6d0c67411bc](https://user-images.githubusercontent.com/31655780/36694603-da737c06-1b0c-11e8-9278-11deb1e91abd.jpeg)

### Screenshots/Video ###
*Paste screenshots here. For video, compress and attach*

**Comment by mahestro** [comment]
Duplicate #72
