### ISSUE TITLE
Search options in the dropdown under parameters are not inclusive enough

### ISSUE THREAD

**Issue by bckingsbury** [topcoderinc/mjolnir-web#118]
### OS and Browser Details ###
*Ipad Pro - 11.2.6
### Screen Name where the issue occurs ###
*parameters page under the search Section
### Exact Reproduction Steps ###
1. Have opportunities toggled in the parameters page and click on the first dropdown menu in three search sentence. 
2. 

### Actual  Result ###
See attached

### Expected Result ###
See attached

### Screenshots/Video ###
*Paste screenshots here. For video, compress and attach*
![8152efd1-5038-4770-bdde-3b56a5013e2e](https://user-images.githubusercontent.com/31655780/36698193-39ca8820-1b17-11e8-9b65-2785c03d274e.jpeg)

**Comment by mahestro** [comment]
This will be better populated once backend services are integrated.
