### ISSUE TITLE
Picture of User is not represented in the Edit user profile screen

### ISSUE THREAD

**Issue by bckingsbury** [topcoderinc/mjolnir-web#124]
### OS and Browser Details ###
*Ipad Pro - 11.2.6
### Screen Name where the issue occurs ###
*Edit User Screen
### Exact Reproduction Steps ###
1. Go to the edit user screen
2. 

### Actual  Result ###
See attached

### Expected Result ###
See attached

### Screenshots/Video ###
*Paste screenshots here. For video, compress and attach*
![eff0fb47-eba9-4d9c-b6a1-f2da1e213c86](https://user-images.githubusercontent.com/31655780/36698959-548f1afc-1b19-11e8-9871-51ee7c342e51.jpeg)

**Comment by mahestro** [comment]
Dup #133
