### ISSUE TITLE
When trying to change the user subscription the boost page appears for some reason

### ISSUE THREAD

**Issue by bckingsbury** [topcoderinc/mjolnir-web#131]
### OS and Browser Details ###
*iPad Pro - 11.2.6
### Screen Name where the issue occurs ###
*edit subscription Screen *

### Exact Reproduction Steps ###
1. Try to edit the user subscription
2. 

### Actual  Result ###
See attached

### Expected Result ###
See attached

### Screenshots/Video ###
*Paste screenshots here. For video, compress and attach*
![d335bd25-9882-458c-9e40-ecc9f5b4f0a6](https://user-images.githubusercontent.com/31655780/36700447-b8b43360-1b1d-11e8-9734-f1baa9887693.jpeg)

**Comment by mahestro** [comment]
Merging with #132
