### ISSUE TITLE
Website-PC: Business Profile build=>section 7=>button doesn’t  Work and is labeled worng

### ISSUE THREAD

**Issue by nithyaasworld** [topcoderinc/mjolnir-web#16]
_From @bckingsbury on January 10, 2018 20:43_

1)Should be labeled ”Add Another Administrator” not office manager

2) It should bring up another set of fields identical to the ones above it that show up below the ones already filled out. Instead it doesn’t nothing. 

_Copied from original issue: topcoderinc/mjolnir-app#401_

**Comment by mahestro** [comment]
Fixed.
