### ISSUE TITLE
Website-PC:business profile build=>section 11=>missing the Facebook, google, and yell logo’s in the boxes

### ISSUE THREAD

**Issue by nithyaasworld** [topcoderinc/mjolnir-web#19]
_From @bckingsbury on January 10, 2018 20:50_

![image](https://user-images.githubusercontent.com/31655780/34794843-f3bd126c-f61d-11e7-8a2e-834245b61711.jpg)

_Copied from original issue: topcoderinc/mjolnir-app#404_

**Comment by mahestro** [comment]
Odd - I can see it http://take.ms/c9z5o
