### ISSUE TITLE
Website-PC:business profile build=>section 9=>Skip and Skip to End buttons should never move with the adding of boxes

### ISSUE THREAD

**Issue by nithyaasworld** [topcoderinc/mjolnir-web#21]
_From @bckingsbury on January 10, 2018 20:55_

It is cut off of my screen now. It should stay right next to the section title “Build your Employee Organization”
![image](https://user-images.githubusercontent.com/31655780/34795028-ac11cd3a-f61e-11e7-9363-9652dd732b50.jpg)

_Copied from original issue: topcoderinc/mjolnir-app#406_

**Comment by mahestro** [comment]
I discussed with the developer. It seems technically difficult to find a solution for this other than a scroll bar as in this video: http://take.ms/kuFql

Do you think that would be ok? @bckingsbury

**Comment by bckingsbury** [comment]
The scroll bar is perfect. That is not the issue here. The problem, and you can also see it in your video, is that the "Skip to the End" button is cut off

**Comment by mahestro** [comment]
Ah perfect, I think that can be fixed. Thanks for the clarification.
