### ISSUE TITLE
Login format issue

### ISSUE THREAD

**Issue by rchristenson** [topcoderinc/mjolnir-web#24]
![image](https://user-images.githubusercontent.com/31657407/34952574-3472c284-f9e8-11e7-84e7-f6794b75469d.png)

**Comment by mahestro** [comment]
May I please know the OS and browser that was used during this test? @bckingsbury @rchristenson

**Comment by bckingsbury** [comment]
Thats a question for @rchristenson

**Comment by bckingsbury** [comment]
Also @mahestro, should this issue be under the web repository? or the app repository?

**Comment by rchristenson** [comment]
No, this is a web issue. The screen grab attached is from a web browser.

I was/am using Windows 10 on an IE 10 browser. 

Per the images attached you can see that the words are being split from one line to the next. Resizing or stretching the page did not seem to help.

![image](https://user-images.githubusercontent.com/31657407/35748818-5435f3be-081d-11e8-8b71-588a3afcf5a2.png)

![image](https://user-images.githubusercontent.com/31657407/35748837-6bd7caba-081d-11e8-8672-efb2f1e6f0d9.png)

![image](https://user-images.githubusercontent.com/31657407/35748868-814f49cc-081d-11e8-82fe-6157a2e9cf1d.png)

**Comment by mahestro** [comment]
I could reproduce it now. Thanks for the info. I will get this fixed next week.
