### ISSUE TITLE
Where did you hear about us choice not color

### ISSUE THREAD

**Issue by rchristenson** [topcoderinc/mjolnir-web#27]
### Win 10 Microsoft Edge 41.16299.15.0  ###
*Example: Windows 10 Chrome63 / Mac OS 10.13.1 Safari11 *

### https://web-app-app.herokuapp.com/register-frame-page ###
*Example: Create Business Profile Screen/ Benches Screen / Settings Screen *

### Exact Reproduction Steps ###
1. From the ODM home page I clicked "Sign up Free"
2. Put in my Name, email and PW clicked 
3. Clicked Create Your Account
4. On the "Where did you hear about us?" page is where the issue is

### Actual  Result ###
Clicked in any box of "Where did you hear about us". When clicking in any of the boxes they did not fill with Color like they do in the mobile app

### Expected Result ###
When clicking in the box of my choice, it should turn the logo in a full accurate color logo representation of the media used to find ODM — https://marvelapp.com/63cf26b/screen/30647233

### Screenshots/Video ###
![image](https://user-images.githubusercontent.com/31657407/35010287-63005984-fad0-11e7-87cd-de03d59197ca.png)

**Comment by mahestro** [comment]
Fixed.
