### ISSUE TITLE
Office Profile build=>section 6=>times need to be corrected

### ISSUE THREAD

**Issue by bckingsbury** [topcoderinc/mjolnir-web#28]
### OS and Browser Details ###
Windows 10, Chrome browser
### Screen Name where the issue occurs ###
Section 6, Hours of Operation, in the office profile build section
### Exact Reproduction Steps ###
1.clicking on the opening and closing hour drop downs. 

### Actual  Result ###
The Opening times allowed are 1-7 only
The closing times allowed are the word "End", then 2-24"

### Expected Result ###
The opening and closing times should be between 1-12. There needs to be a way to distinguish between AM and PM, and also there needs to be the option of opening or closing at a times different that just exactly on the hour, like 8:30am opening with a 6:15pm closing (Using this solely as an example. 

### Screenshots/Video ###
![download 1](https://user-images.githubusercontent.com/31655780/35747809-c0de9628-0819-11e8-9edd-56b0c1e0294c.png)
![download 2](https://user-images.githubusercontent.com/31655780/35747810-c0f09e90-0819-11e8-8cf7-3dc0940e92a7.png)

**Comment by mahestro** [comment]
Duplicate #54
