### ISSUE TITLE
The information being inputted into the profile sections does not, and needs to, follow standard formats.  

### ISSUE THREAD

**Issue by bckingsbury** [topcoderinc/mjolnir-web#29]
### OS and Browser Details ###
Windows 10, Chrome browser
### Screen Name where the issue occurs ###
most profile build sections
### Exact Reproduction Steps ###
inputting information

### Actual  Result ###
any information that is inputted is allowed
### Expected Result ###
incorrect information, like an invalid email address, invalid united states phone number, invalid zip code, invalid address, invalid anything(numbers where letters should be and letters where numbers should be) should become a red box and the user shouldn't be allowed to progress in the profile build until it is corrected, unless it is in a section where a skip or skip to the end button is. 

The screen shots below show what the fields look like before incorrect input, after incorrect input, and the third shows that I can progress to the next section without correcting anything. 

Every section of the profile builds(Office and User) where a specific type of information must be typed in, its important that if that type of information has a format (Phone number, email, address, etc) that the format is followed so that the information being inputted is as correct as possible. We do not want a bunch of bad profile on the site. 

### Screenshots/Video ###

![download 3](https://user-images.githubusercontent.com/31655780/35748180-17f2e1ac-081b-11e8-90e7-7f13c2195931.png)
![download 4](https://user-images.githubusercontent.com/31655780/35748181-18003cbc-081b-11e8-82df-aefae75c2db8.png)
![download 5](https://user-images.githubusercontent.com/31655780/35748182-180feb94-081b-11e8-845f-41ba46f570b4.png)

**Comment by mahestro** [comment]
I understand. The web prototype doesn't include - yet - input validation. This logic is added to the prototype once the backend integration competitions take place. For this exercise (prototype), some data-dependent validations will be missing as well as storing data. Just FYI.
