### ISSUE TITLE
Add horizontal scroll capability indicator

### ISSUE THREAD

**Issue by mahestro** [topcoderinc/mjolnir-web#34]
### OS and Browser Details ###
Mac OS 10.13.3 / Chrome63

### Screen Name where the issue occurs ###
Benches and Friends pages.

### Actual  Result ###
It's hard to tell the horizontal items are scrollable (visually).

### Expected Result ###
Make horizontal scrollbars visible all the time to indicate a status of scroll capability.

**Comment by srajas0** [comment]
@mahestro Hey, I have fixed scrollbar issue with final fix.

**Comment by srajas0** [comment]
@mahestro This issue has been fixed in final fix

**Comment by mahestro** [comment]
Indeed, thanks.
