### ISSUE TITLE
Floating buttons remain active after closing employer profile overlay

### ISSUE THREAD

**Issue by mahestro** [topcoderinc/mjolnir-web#39]
### OS and Browser Details ###
Mac OS 10.13.3 / Chrome63

### Screen Name where the issue occurs ###
Employer Profile Overlay

### Exact Reproduction Steps ###
1. Open employer profile overlay (route `/profiles/edit`).
2. Scroll down.
3. Click outside of the overlay.

### Actual  Result ###
Floating buttons remain visible.

### Expected Result ###
Floating buttons should disappear.

### Screenshots/Video ###
http://take.ms/vLv3E

**Comment by srajas0** [comment]
@mahestro This issue has been fixed in final fix
