### ISSUE TITLE
Employer Profile Build out Flow Fix

### ISSUE THREAD

**Issue by mahestro** [topcoderinc/mjolnir-web#41]
### OS and Browser Details ###
Mac OS 10.13.3 / Chrome63

### Screen Name where the issue occurs ###
Create Employer Pages

### Expected Result ###
- Ref: http://take.ms/p12Lm
- After clicking ok in the "Each office profile must have .." popup the user gets to see the Employee buildout process.
- When the user finishes this profile please create a connection popup with a message "You have successfully completed the personal profile, now it's time to continue with the Office profile. – CONTINUE button".
- It opens the Employer profile build out (with the import profile popup over step one).

**Comment by srajas0** [comment]
Flow :
Step 1) Opening this page - https://gyazo.com/a81bc8865541a2d33606a422b5912a0e
Step 2) https://gyazo.com/32348687197d8866840d5aeb17d15811
Step 3) Clicking 'Ok' will showing steps - https://gyazo.com/02be6f2129600c048e8f954cfee1a388
Step 4) User finishes the steps, Showing 'CONNECTION' popup with 'CONTINUE" button
Step 5) Clicking 'CONTINUE' button need to show 'import profile popup'
Step 6) Then, How to redirect to 'Profiles' page?

Previously, we are redirecting to profile page after completing last step ( 12th step ) and when clicking on 'No, I'll do it later' button in 'CREATE AN OFFICE' popup - https://gyazo.com/9b9374660cce5d6623e840697db89e63

**Comment by mahestro** [comment]
Steps 1 - 4 are correct.

Step 5: Clicking 'CONTINUE' button directs the user to the Employer profile build out step one.
Step 6: Show import profile popup.

After finishing the employer profile, it behaves the same, it finishes with the 'copy office' popup. When clicking 'I'll do it later' it goes to the Dashboard (`profiles` page).

**Comment by srajas0** [comment]
Sorry, still not clear.
Then how to show 'CREATE AN OFFICE' popup ?

**Comment by mahestro** [comment]
As it's currently done. That doesn't need changes.

**Comment by srajas0** [comment]
No, Previously, **we are showing 'CREATE AN OFFICE' popup after complete last step ( 12th step ).**

Now you're said, 

Step 4) User finishes the steps ( 12th step), Showing 'CONNECTION' popup with 'CONTINUE" button
Step 5) Clicking 'CONTINUE' button need to show 'import profile popup'

This is my question,
how to show 'CREATE AN OFFICE' popup ?

**Comment by mahestro** [comment]
It's easy to get confused with the flows, no worries. Keep in mind there are **two** different flows and **two** different/unique profile buildout processes – employer and employee.

- Employer flow depends on the employee buildout (#40).
- An employer user must first have a regular employee profile in order to create an employer profile.
- An employee profile doesn't have any dependency (this is what you built on this challenge (well done, just some adjustments needed, see #40).

Just some context FYI, now to the specifics:
- Step 4: When the user finishes the 15th step from **employee** profile, show a 'CONNECTION' popup (with continue button).
- Step 5: Clicking on continue will bring the **employer** page on step one. After completing the 12th step of this page, show the create an office popup.

Let me know if that makes sense.

**Comment by mahestro** [comment]
Final note: The flow from this issue is triggered from activating 'Create a business profile' http://take.ms/IKtxU. **BUT** if the user triggers the another frow (#40) notice that after completing that 15th step user won't need to be redirected to employer profile build out, he would go directly to the dashboard.

I didn't want to mix up both behaviours to avoid confusion but it seemed necessary to add the global context.

**Comment by srajas0** [comment]
Great, I got it :)

**Comment by mahestro** [comment]
Great job @srajas0, it was confusing and you solved it. Thanks.
