### ISSUE TITLE
Incorrect pop up where no pop up is needed while signing up as a User

### ISSUE THREAD

**Issue by bckingsbury** [topcoderinc/mjolnir-web#48]
### OS and Browser Details ###
IPad Pro - OS 11.2.2

### Screen Name where the issue occurs ###
Page where one chooses between creating a user profile and a office profile
### Exact Reproduction Steps ###
1. Choose a user profile
2. 

### Actual  Result ###
The pop up shows up that explains that all Office profile need a user profile to be created first. 

### Expected Result ###
No pop up should come up. The pop up should only come up when an office profile is chosen as the pop up explains why the user needs to create an user profile before the office profile and that is redundant when choosing to create a user profile

### Screenshots/Video ###
![ab3556e4-d923-4a1a-a594-c5460f26e40c](https://user-images.githubusercontent.com/31655780/35916466-7816cb14-0bd8-11e8-9ca4-c30e93b16858.png)

![1010026b-2506-474d-97b3-ff6cffb75593](https://user-images.githubusercontent.com/31655780/35917395-eea40ba4-0bdb-11e8-9b48-8f804c07d47c.jpeg)

**Comment by mahestro** [comment]
Fixed #47
