### ISSUE TITLE
City and Zip Code are incorrect in the user profile build section 1 

### ISSUE THREAD

**Issue by bckingsbury** [topcoderinc/mjolnir-web#52]
### OS and Browser Details ###
IPad Pro - iOS 11.2.2
### Screen Name where the issue occurs ###
User profile build section 1

### Exact Reproduction Steps ###
1. Try to enter a city or zip
2. 

### Actual  Result ###
Aren’t able to enter proper cities or zip codes 

### Expected Result ###
Should be able to enter a city, which should be linked to a database of all cities in the United States and Canada, as well as the zip codes 

### Screenshots/Video ###
![a963b8b5-98b0-4d6f-879c-1524b10acfee](https://user-images.githubusercontent.com/31655780/35918135-aed8efc8-0bde-11e8-8089-071b64569a7c.png)
![7382aeb8-9b7e-425e-8d29-7421973ec8b9](https://user-images.githubusercontent.com/31655780/35918138-af75b542-0bde-11e8-8990-6a813ba784b3.png)

**Comment by mahestro** [comment]
Fixed #38
