### ISSUE TITLE
When creating an Office/Business profile the pop up appears that explains the need to create a User profile first but then the first section of the office profile build appears

### ISSUE THREAD

**Issue by bckingsbury** [topcoderinc/mjolnir-web#55]
### OS and Browser Details ###
IPad Pro - iOS 11.2.2

### Screen Name where the issue occurs ###
Section 1 of the Office profile build

### Exact Reproduction Steps ###
1. Choose to start an office profile
2. 

### Actual  Result ###
Section 1 of the office profile build appears after the pop up explains that the User profile must be created first. 

### Expected Result ###
The User profile section one should appear first, not the office profile build

The screen shots will show the office profile being selected, the pop up explaining that a User profile must be created first, and the office profile build section one appearing, respectively. 

### Screenshots/Video ###
![2910f4bb-8bf7-42cc-af01-d82754bd3a24](https://user-images.githubusercontent.com/31655780/35919626-bcde8b6e-0be3-11e8-9886-ceeccdf5f946.png)
![48e8cb0d-12b8-41da-bb76-75dfcd8dfcc9](https://user-images.githubusercontent.com/31655780/35919630-bd77d7ba-0be3-11e8-9f30-6ab5b27f2802.png)
![ac7a5906-6899-4805-97b6-f33bdaf1a9f4](https://user-images.githubusercontent.com/31655780/35919631-be1c63fc-0be3-11e8-81a5-fd82bd1fc811.png)

**Comment by mahestro** [comment]
Fixed #47
