### ISSUE TITLE
After the pop up that allows someone to import pictures from different social sites, it is not possible to add more pictures from those site, only pictures from the camera or from the local photo library. Also pictures don’t actually upload and appear in the boxes

### ISSUE THREAD

**Issue by bckingsbury** [topcoderinc/mjolnir-web#57]
### OS and Browser Details ###
IPad Pro - iOS 11.2.2
### Screen Name where the issue occurs ###
Section 4 of the User profile build

### Exact Reproduction Steps ###
1. Try to upload a picture
2. 

### Actual  Result ###
A pop up appears that doesn’t have all the options for upload pictures, and the pictures that are loaded don’t appear

### Expected Result ###
The proper pop up with all the desired photo options should appear and when the pictures are chosen they should be upload and appear in the box that the user clicked on. 
### Screenshots/Video ###
The first pic shows what happens after trying to upload two pictures from my camera and my photo library. 

![81695c67-62a5-409b-9523-5ad34adf6283](https://user-images.githubusercontent.com/31655780/35920871-1da8010c-0be7-11e8-856d-f636ebeb5926.png)

The second picture shows what appears when clicking on one of the boxes to upload a picture

![8f950fd6-9faa-454a-aa83-e3b95ba40856](https://user-images.githubusercontent.com/31655780/35920895-2f6f7848-0be7-11e8-873a-d254a387e7ea.png)

The third shows what pop up should appear and all the options we want the user to be able to choose from. Its a screenshot of the mobile but regardless the pop up contents will be the same. 

![6dd975fe-6d79-49cb-8ae1-471193443144](https://user-images.githubusercontent.com/31655780/35920923-49162fda-0be7-11e8-8b0c-47c51636824b.png)

**Comment by mahestro** [comment]
This functinoality is not in scope for a prototype, it's a dev operation. It will be handled in those competitions/tasks. Closing.
