### ISSUE TITLE
There needs to be an “Other” box for people to input unlisted software in Section 5 of the User profile build

### ISSUE THREAD

**Issue by bckingsbury** [topcoderinc/mjolnir-web#58]
### OS and Browser Details ###
IPad Pro - iOS 11.2.2

### Screen Name where the issue occurs ###
Section 5 of the User profile build

### Exact Reproduction Steps ###
1. Going to that section
2. 

### Actual  Result ###
There is no other field for inputting unlisted softwares
### Expected Result ###
There needs to be an Other field

### Screenshots/Video ###
![2707d158-b2c5-46d8-a4c0-72a74316d363](https://user-images.githubusercontent.com/31655780/35921987-4a73611a-0bea-11e8-92bf-ae25941dbebf.jpeg)

**Comment by mahestro** [comment]
#96
