### ISSUE TITLE
When completing the User profile build an unnecessary pop up appears

### ISSUE THREAD

**Issue by bckingsbury** [topcoderinc/mjolnir-web#59]
### OS and Browser Details ###
IPad Pro - iOS 11.2.2
### Screen Name where the issue occurs ###
After section 15 of the User profile build

### Exact Reproduction Steps ###
1. Complete section 15 or click skip to the end button starting at section 5
2. 

### Actual  Result ###
Create Another office pop up appears

### Expected Result ###
No pop up should appear. Instead the user should be sent to the main profiles page of the app. That pop up is only relevant after one has created the Office profile build. 

### Screenshots/Video ###
![383d42e6-8e2e-4e45-b8e6-1c7104200c3f](https://user-images.githubusercontent.com/31655780/35922193-f1e3e30c-0bea-11e8-9888-d0471b774166.png)

**Comment by mahestro** [comment]
Duplicate #40
