### ISSUE TITLE
Website: The logo and input fields fade in too late on the Signup Screen

### ISSUE THREAD

**Issue by nithyaasworld** [topcoderinc/mjolnir-web#6]
_From @bckingsbury on January 10, 2018 20:17_

The Fade in over the video is nice but needs to happen sooner. Maybe after 3 seconds. 

_Copied from original issue: topcoderinc/mjolnir-app#391_

**Comment by mahestro** [comment]
Noted that too. I asked to be 1.5 sec. 3 seconds is still too long, it doesn't seem to be good user experience; I got to think the page didn't work :)
