### ISSUE TITLE
Office Profile Web build - When are you open for business? Time issue

### ISSUE THREAD

**Issue by rchristenson** [topcoderinc/mjolnir-web#60]
WIN 10 Microsoft Edge 41.16299.15.0  Dell XPS
*Example: Windows 10 Chrome63 / Mac OS 10.13.1 Safari11 *

https://mjolnir-web-prototype.herokuapp.com/register-frame-page

### Exact Reproduction Steps ###
1. Going through Business profile build
2. Got to the "When are you open for business?" Section where you put in your open and close times for each day

### Actual  Result ###
Starting with Monday, when I click to open the "Open time" drop down I can see hours 1-6 only, no scroll bar showing
When i click to open the "Close time" drop down I can see only the hours from 6-24 and there is a scroll bar
Time is showing as plan numbers, 1, 2, 3, 4, 5 - 24 not Time

### Expected Result ###
I should click the "Open time" drop down and see 1:00AM - 12:00PM, via a scroll bar
I should click the "Close time" drop down and see 1:00AM - 12:00PM, via a scroll bar
The times should show up using a time format, ie 8:00am, 12:00am, 5:00pm, 12:00pm

### Screenshots/Video ###
*Paste screenshots here. For video, compress and attach*
![image](https://user-images.githubusercontent.com/31657407/35922430-90b62f3a-0beb-11e8-8bb6-87f220b421e6.png)

**Comment by mahestro** [comment]
Duplicate #54
