### ISSUE TITLE
Section 12 of User Profile build there needs to be an “Add Another Peer” button

### ISSUE THREAD

**Issue by bckingsbury** [topcoderinc/mjolnir-web#61]
### OS and Browser Details ###
IPad Pro - iOS 1.2.2
### Screen Name where the issue occurs ###
Section 12 of the User profile build
### Exact Reproduction Steps ###
1. Try to add another peer and there is no button to
2. 

### Actual  Result ###
There is no button to add another peer.
### Expected Result ###
There should be a button to add another peer and then when pressed a new set of field to add that peer should appear below the field that have already been inputted. 

### Screenshots/Video ###
![12c15744-d4a5-45e4-a116-d2eaa510e18b](https://user-images.githubusercontent.com/31655780/35922620-0368fb02-0bec-11e8-9830-f47a8c3a27c6.jpeg)

**Comment by mahestro** [comment]
It was not in the design, that's why it was skipped.

@srajas0, it should be straight forward to reuse the code for this from the employer profile build out, right? Same codebase.

**Comment by mahestro** [comment]
#96
