### ISSUE TITLE
Can’t progress after section 15 without hitting the skip button.

### ISSUE THREAD

**Issue by bckingsbury** [topcoderinc/mjolnir-web#63]
### OS and Browser Details ###
IPad Pro - iOS 11.2.2
### Screen Name where the issue occurs ###
Section 15 of the User profile build

### Exact Reproduction Steps ###
1. After inputting a description then the only way to progress to the app is to click the “skip” button
2. 

### Actual  Result ###
Described above

### Expected Result ###
There should be no “Skip” button at the last section of the profile build. Instead there should be a button below the description that is labeled “Complete Profile, Finally”

### Screenshots/Video ###
![d31e88a7-f6cc-42d4-bd40-348428d979ea](https://user-images.githubusercontent.com/31655780/35923631-ca4e2ec0-0bee-11e8-8f98-99e9437c3bdf.jpeg)

**Comment by mahestro** [comment]
#96
