### ISSUE TITLE
Need a small tweak with the animation when toggling the Friends/Opportunities button in the Profiles section of the app

### ISSUE THREAD

**Issue by bckingsbury** [topcoderinc/mjolnir-web#65]
### OS and Browser Details ###
IPad Pro - iOS 11.2.2
### Screen Name where the issue occurs ###
Profile section of the app
### Exact Reproduction Steps ###
1. Pressing the friends button or the opportunities button
2. 

### Actual  Result ###
There is an animation that is cool but has a phantom card that is between the bottom of the screen and the stack of cards

### Expected Result ###
That phantom card can be removed and the rest of the animation keep the same and the it would look much better. 

### Screenshots/Video ###
The screen shot attached illustrates the above description and request. 

![51f24062-56ec-4c7b-b7e0-9770f5f3bffc](https://user-images.githubusercontent.com/31655780/35924413-004234ca-0bf1-11e8-9103-7d8fde589036.jpeg)

**Comment by mahestro** [comment]
Duplicate #64
