### ISSUE TITLE
Need pop ups after pressing buttons that appear after clicking on the Multi-use Button on the main profiles page. 

### ISSUE THREAD

**Issue by bckingsbury** [topcoderinc/mjolnir-web#66]
### OS and Browser Details ###
IPad Pro - iOS 11.2.2
### Screen Name where the issue occurs ###
Multi use button the main Profiles page of the app

### Exact Reproduction Steps ###
1. Press the multi use button
2. Press either the share profile or request endorsement buttons

### Actual  Result ###
Nothing happens

### Expected Result ###
Corresponding pop ups should appear and function. 

### Screenshots/Video ###
![b40a5b9c-0735-490e-b293-8418a9128074](https://user-images.githubusercontent.com/31655780/35925019-9daa8f9a-0bf2-11e8-8db9-9423dcd182ed.png)
![eeed4aa9-4717-404e-9ff3-3e1384d6406c](https://user-images.githubusercontent.com/31655780/35925020-9e319238-0bf2-11e8-8e02-751aee35fd86.jpeg)

**Comment by mahestro** [comment]
@srajas0 FYI:

- Multi use button: http://take.ms/CkROc
- Clicking share profile should bring the share popup, you already have it.
- Clicking endorsement brings the ask for endorsements popup right on the same dashboard page.
- Add first name, last name fields to the ask for endorsements popup in this scenario (dashboard) and also in the endorsement request view.

Thanks!

**Comment by mahestro** [comment]
Fixed #97
