### ISSUE TITLE
In the friends and benches sections the cards and conversations are not responsive when clicking on them. 

### ISSUE THREAD

**Issue by bckingsbury** [topcoderinc/mjolnir-web#67]
### OS and Browser Details ###
IPad Pro - iOS 11.2.2
### Screen Name where the issue occurs ###
Friends and Benches section
### Exact Reproduction Steps ###
1. Clicking on a card or on a message
2. 

### Actual  Result ###
Neither respond at all

### Expected Result ###
When clicking on a card that card should grow to envelope the entire screen and display the profile associated with that card. An arrow (<-) should appear at the top let of the expanded profile to allow the user to collapse that profile back to a card

When clicking on a message with a user then that conversation should expand to envelope the entire screen. In the top left corner of that expanded conversation there should be an arrow pointing to the left that when clicked collapses the conversation back down to the section it was in. 

### Screenshots/Video ###
There is no screen shot to show the lack of action.

**Comment by mahestro** [comment]
Next phase.
