### ISSUE TITLE
SOS feature does not have the appropriate position represented in the drop down. 

### ISSUE THREAD

**Issue by bckingsbury** [topcoderinc/mjolnir-web#68]
### OS and Browser Details ###
IPad Pro - iOS 11.2.2
### Screen Name where the issue occurs ###
Benches section of the app

### Exact Reproduction Steps ###
1. Clicking on the SOS button
2. Then clicking on the drop down for the position you need to quickly fill

### Actual  Result ###
Three incorrect options are presented

### Expected Result ###
All of the positions that a user can hold should be able to be chosen, in alphabetical order. 

### Screenshots/Video ###
The screen shot is of all available positions

![efe977d6-c9a3-4fd3-9983-1a3551998010](https://user-images.githubusercontent.com/31655780/35925944-01bedd2c-0bf5-11e8-9266-9d588cfc6af8.jpeg)

**Comment by mahestro** [comment]
Dev.
