### ISSUE TITLE
Office profile build allowed before a personal profile is created

### ISSUE THREAD

**Issue by rchristenson** [topcoderinc/mjolnir-web#69]
Windows 10 Microsoft Edge 41.16299.15.0 Dell XPS
*Example: Windows 10 Chrome63 / Mac OS 10.13.1 Safari11 *

### Screen Name where the issue occurs ###
https://mjolnir-web-prototype.herokuapp.com/register-frame-page 

### Exact Reproduction Steps ###
1. Starting down the Office Profile sign up path
2. I get to the page where you select to build either an office or personal profile
3. I selected Office profile then hit "Lets Start"
4. Pop up opens explaining I need a personal profile before I can build an office profile (This is correct and should happen)
5. Then I click the "OK" button to close the pop up
6. I am then taken to the office profile build page which is not correct. I should not be able to get to the office profile build until I at least have a base personal profile built

### Actual  Result ###
When selecting to create an office profile before I have a personal profile I am prompted by a pop up that I need to create a personal profile first and am then taken to the start of the office profile build

### Expected Result ###
When attempting to create an office profile I should be prompted by the pop up that I need a personal profile first and then taken directly to the Personal Profile build start page

### Screenshots/Video ###
*Paste screenshots here. For video, compress and attach*
![image](https://user-images.githubusercontent.com/31657407/35926203-9c1f4528-0bf5-11e8-8163-4a9f774fb955.p

**Comment by mahestro** [comment]
Duplicate #41
