### ISSUE TITLE
Website: After typing in my name, email address and password when first signing on I get this message

### ISSUE THREAD

**Issue by nithyaasworld** [topcoderinc/mjolnir-web#7]
_From @bckingsbury on January 10, 2018 20:22_

![add2a820-f831-4e7f-a0eb-66a63e53c829](https://user-images.githubusercontent.com/31655780/34793622-0f66f87e-f61a-11e7-9608-5362a21f1176.jpeg)

I also don’t get an email but am able to keep going.

_Copied from original issue: topcoderinc/mjolnir-app#392_

**Comment by mahestro** [comment]
This is a mockup. It doesn't have services integrated (it will work after it goes to development integration). Closing.
