### ISSUE TITLE
When adding a Bench the new bench does not populate the benches section

### ISSUE THREAD

**Issue by bckingsbury** [topcoderinc/mjolnir-web#70]
### OS and Browser Details ###
IPad Pro - iOS 11.2.2
### Screen Name where the issue occurs ###
Benches section

### Exact Reproduction Steps ###
1. Click the “+” sign at the bottom of the page
2. Click to add a bench

### Actual  Result ###
After naming and adding the new bench the pop up disappears but the new bench does not populate the benches section

### Expected Result ###
The new bench should populate the benches section. 

### Screenshots/Video ###
The screen shots shows me naming a new bench. After the pop up disappears after I press the add button, no bench populates 

![da60020d-4c1f-4386-9047-3ccc966a77f2](https://user-images.githubusercontent.com/31655780/35926243-b2907692-0bf5-11e8-9a8e-0ef362c0c52e.png)

**Comment by mahestro** [comment]
Dev.
