### ISSUE TITLE
Need to have a mechanism of action to reorganize the benches

### ISSUE THREAD

**Issue by bckingsbury** [topcoderinc/mjolnir-web#71]
### OS and Browser Details ###
IPad Pro - iOS 11.2.2
### Screen Name where the issue occurs ###
Benches section of the app

### Exact Reproduction Steps ###
1. Clicking and holding on one of the benches highlighted it but does not eventually allow it to be moves around
2. 

### Actual  Result ###
Described above

### Expected Result ###
Clicking and holding should allow for the bench to be reorganized. That or perhaps some other mechanism of action to accomplish the same goal. On the mobile app its a hard press and then one is able to reposition the bench. 

### Screenshots/Video ###
There is no screen shot I could take to illustrate this.

**Comment by mahestro** [comment]
The functionality exists. First you must click the edit (pencil) icon to be allowed to organize, as described in the marvelapp/devnotes cc @bckingsbury
