### ISSUE TITLE
Incorrect toggle button on the Search page. 

### ISSUE THREAD

**Issue by bckingsbury** [topcoderinc/mjolnir-web#75]
### OS and Browser Details ###
*iPad Pro - iOS 11.2.2
### Screen Name where the issue occurs ###
Search section of the app
### Exact Reproduction Steps ###
1. Go to the search section of the app
2. 

### Actual  Result ###
The toggle button in the top middle of this page says Friends/Potential Hires

### Expected Result ###
The toggle button should say Friends/Opprotunities just like it does in the Profiles section of the app

I am viewing the app as a User, which is what is highlighted in the Users section of the app. Since I am an individual looking for a job I should only be presented with the potential to search for Friends or Opportunities. 

### Screenshots/Video ###
The first screen shot is of the user profile being highlighted in the Users section of the app. 

![b7c955b4-35bf-4f12-a703-207cb656e887](https://user-images.githubusercontent.com/31655780/35928568-78b51224-0bfb-11e8-8cfa-05c7fea5e7a5.jpeg)

The second screenshot shows the toggle button and what it should say

![37629522-e5bf-4d58-99e6-8048d1df67f5](https://user-images.githubusercontent.com/31655780/35928606-8e9e1fe0-0bfb-11e8-9b58-3f0283c3aca2.jpeg)

**Comment by mahestro** [comment]
User management will be handled in services integration/dev next phase.

Closing.
