### ISSUE TITLE
The highlighted words in the search parameters section need to have their drop down menus changed

### ISSUE THREAD

**Issue by bckingsbury** [topcoderinc/mjolnir-web#76]
### OS and Browser Details ###
IPad Pro - iOS 11.2.2

### Screen Name where the issue occurs ###
The parameters page in the Search section of the app. 

### Exact Reproduction Steps ###
1. Click on the parameters button in the search section of the app
2. 

### Actual  Result ###
There are five highlighted words that when pressed turn into dropdown menus. We need to change the options for each dropdown. 

### Expected Result ###
1. The first dropdown needs have all the possible positions that someone can choose to have when creating a user profile

2. The second is the number fo years experience and that should be less than 1, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10+ years

3. The third is the distance from the location that the user picked. Those options should be 5, 10, 25, 50, 100, 200 miles

4. The fourth is location and that should have an input field for a city/state and a zipcode(the user can use either one to pic the city or zipcode they want to search from

5. The fifth is the duration of time since using the app. The options should be within 1 day, 1 week, 1 month, 1 year

### Screenshots/Video ###

![Uploading D7646424-6A71-4A26-A84E-3CF73A7C0463.png…]()

**Comment by mahestro** [comment]
1. Will be properly filled in the next phase - @srajas0 ignore.
4. Replace with popup when clicking, not dropdown.

**Comment by srajas0** [comment]
@mahestro I don't understand, what we need to be done here? I already implemented as dropdown, please provide screen shot and explain

**Comment by mahestro** [comment]
Sorry @srajas0, the numbered list went wrong, [I meant 4](http://take.ms/k5R4eV) but it changed it to 2. 

The location popup should be one of those we already use in the app, with an autocomplete field labeled "City or Zipcode" ~ http://take.ms/BQJ5B.

**Comment by srajas0** [comment]
So, only need to change LOCATION should be autocomplete   
[![Screenshot from Gyazo](https://gyazo.com/652e1840b4e67b20240a9f43cce60b1e/raw)](https://gyazo.com/652e1840b4e67b20240a9f43cce60b1e)

**Comment by mahestro** [comment]
Yes, it will open a popup as illustrated in my previous message.

**Comment by srajas0** [comment]
Please confirm, my understanding is correct or not?

Expected Result will be like this, right?
[![Screenshot from Gyazo](https://gyazo.com/f3ee8227bc7c23794a13c723c9fa453d/raw)](https://gyazo.com/f3ee8227bc7c23794a13c723c9fa453d)

**Comment by mahestro** [comment]
Yes. It would need to display only one text field labeled "City or Zipcode". This textfield should be displayed within a popup, as in the image http://take.ms/BQJ5B

**Comment by mahestro** [comment]
Fix #97
