### ISSUE TITLE
Incorrect buttons on pop up notifications

### ISSUE THREAD

**Issue by bckingsbury** [topcoderinc/mjolnir-web#77]
### OS and Browser Details ###
IPad Pro - IOS 11.2.2
### Screen Name where the issue occurs ###
Any screen
### Exact Reproduction Steps ###
1. Pop up notifications
2. 

### Actual  Result ###
The buttons on the pop up are incorrect

### Expected Result ###
That the buttons are correct. 

Screenshots attached

### Screenshots/Video ###
![d4e4463f-b527-43d0-8de2-a86e0e541fb9](https://user-images.githubusercontent.com/31655780/35977669-bee3cb12-0cb1-11e8-88e4-af9ddd123d94.jpeg)
![b9537b40-396c-4ec9-bb8d-c7948843895e](https://user-images.githubusercontent.com/31655780/35977708-d9860d72-0cb1-11e8-9e52-c9f5991c2996.jpeg)
![052b49f2-7280-4ce1-aa5d-56bd12eb6fa9](https://user-images.githubusercontent.com/31655780/35977781-fc96c8a6-0cb1-11e8-9071-12dbab9911a9.jpeg)

**Comment by mahestro** [comment]
Duplicate #44
