### ISSUE TITLE
Website: trying to signup for a User Profile but two wrong things happen

### ISSUE THREAD

**Issue by nithyaasworld** [topcoderinc/mjolnir-web#8]
_From @bckingsbury on January 10, 2018 20:26_

1) The pop up that should show up when one clicks on “Create a business profile” pop up. That should only happen when someone chooses to set up a business profile, not a User profile like I did. 

2)After the pop up the business profile is behind it instead of the User profile. 

_Copied from original issue: topcoderinc/mjolnir-app#393_

**Comment by mahestro** [comment]
This is scoped to be completed in the follow up prototype challenge. Closing.
