### ISSUE TITLE
Can not edit the custom filters in the parameters page

### ISSUE THREAD

**Issue by bckingsbury** [topcoderinc/mjolnir-web#80]
### OS and Browser Details ###
IPad Pro - iOS 11.2.2

Custom Filters page of the parameters page

### Exact Reproduction Steps ###
1. Go to the custom filters page of the parameters section
2. 

### Actual  Result ###
Can’t edit the filters to delete them or reorganize them
### Expected Result ###
Should be able to edit and reorganize
### Screenshots/Video ###
![ef2121a0-63bc-4751-be2d-48c4a72f6489](https://user-images.githubusercontent.com/31655780/35979240-d407019a-0cb5-11e8-8635-e837d3fe370c.jpeg)

**Comment by mahestro** [comment]
Next phase.
