### ISSUE TITLE
Need to ensure that the information in the top right corner of every page is the representative of the way the user is viewing the app. 

### ISSUE THREAD

**Issue by bckingsbury** [topcoderinc/mjolnir-web#82]
### OS and Browser Details ###
IPad Pro - 11.2.2
### Screen Name where the issue occurs ###

All screens

### Exact Reproduction Steps ###
1. Go to any screen
2. 

### Actual  Result ###
The user is displayed

### Expected Result ###
We need to ensure that the information in the top right corner is representative of the way the user is viewing the app. If the user has their user profile selected in the User’s section of the app then it should be reflected in the top right corner of every screen. 

If the user has one of their office profiles selected then that profile should be represented there instead. 

### Screenshots/Video ###
![70f817db-a512-4ed1-93ff-a74fe1751416](https://user-images.githubusercontent.com/31655780/36008647-9adfad72-0d05-11e8-8c0e-a66eb0466f74.jpeg)

**Comment by mahestro** [comment]
Next phase.
