### ISSUE TITLE
Word of Mouth not showing up in color

### ISSUE THREAD

**Issue by rchristenson** [topcoderinc/mjolnir-web#83]
### OS and Browser Details ###
Win 10 Microsoft Edge 41.16299.15.0 Dell XPS

### Screen Name where the issue occurs ###
https://mjolnir-web-prototype.herokuapp.com/register-frame-page

### Exact Reproduction Steps ###
1. Getting to the page where you select "How did you hear about us?"
2. The first option in the top left hand corner "Word of mouth" is not showing up in color once selected.

### Actual  Result ###
When selecting "Word of mouth" it does not pop up in color

### Expected Result ###
When selecting "Word of mouth" it should fill with color, like in the mobile app

### Screenshots/Video ###
![image](https://user-images.githubusercontent.com/31657407/36007229-91a244b8-0d0f-11e8-9425-7ff0bbda632f.png)

**Comment by mahestro** [comment]
@srajas0 Can you please help with this one? These are the source files of the icons: https://drive.google.com/open?id=0B1hQWnfwpYvrbzRVcFBReFhZN1k (Employer Profile Build.ai)

**Comment by srajas0** [comment]
Could you please provide **Word Of Mouth** active icon. I don't have .ai.

**Comment by mahestro** [comment]
You can use this one attached.

![word-icon](https://user-images.githubusercontent.com/729632/36086825-cd74b518-0fce-11e8-80e8-5de1330fdebe.png)

**Comment by mahestro** [comment]
Fixed #97
