### ISSUE TITLE
Org chart should not be editable until the pen has been pressed

### ISSUE THREAD

**Issue by mahestro** [topcoderinc/mjolnir-web#84]
### OS and Browser Details ###
Mac OS 10.13.3 / Chrome63

### Screen Name where the issue occurs ###
Employer Profile Edit Mode

### Expected Result ###
Org chart should not be editable until the pen has been pressed. Hide or disable the "plus signs" before it's in edit mode.

**Comment by srajas0** [comment]
@mahestro This has been fixed in final fix
