### ISSUE TITLE
Registration page not formatting correctly when clicking to next section

### ISSUE THREAD

**Issue by rchristenson** [topcoderinc/mjolnir-web#87]
### OS and Browser Details ###
Win 10 Microsoft Edge 41.16299.15.0  Dell XPS

### Screen Name where the issue occurs ###
https://mjolnir-web-prototype.herokuapp.com/register-frame-page

### Exact Reproduction Steps ###
1. Going through the Personal registration page on a Win 10 machine using MS edge
2.  Filled in the #1 section "Personal Details"
3. Clicked on #2 What do you do in the dental world?
4. #2 section expanded open but did not scroll up and end with the top of the #2 section being at the top
5. I tried to do the same thing with #3 - 5 with the same result

### Actual  Result ###
Going through the registration process and clicking through the next sections it would not roll up and format so the next section was sitting on top of the page

### Expected Result ###
When I click on the next section it should scroll up and have the next section title be at the top of the page

### Screenshots/Video ###

Clicked on #2 and ended up here
![image](https://user-images.githubusercontent.com/31657407/36034094-f11be87e-0d80-11e8-90f9-10de557cf4a2.png)

Cliecked on #6 and ended up here
![image](https://user-images.githubusercontent.com/31657407/36034147-11724a8c-0d81-11e8-8adf-29f7d64994f4.png)

**Comment by mahestro** [comment]
Duplicate #53
