### ISSUE TITLE
Image upload option missing

### ISSUE THREAD

**Issue by rchristenson** [topcoderinc/mjolnir-web#88]
### OS and Browser Details ###
Win 10 Microsoft Edge 41.16299.15.0 Dell XPS

### Screen Name where the issue occurs ###
https://mjolnir-web-prototype.herokuapp.com/register-frame-page

### Exact Reproduction Steps ###
1. Going through the Personal Profile registration process
2. Got to step 4 where you upload images
3. There is not a way to select upload an image from your PC

### Actual  Result ###
The popup to select where you want to import photos from includes Google plus, Instagram, facebook and Photos

### Expected Result ###
When this popup opens it should include an option to select photos from your PC
This may be the "Photos" option already on there but it should be more clear and say select from your PC or something like that

### Screenshots/Video ###
![image](https://user-images.githubusercontent.com/31657407/36063138-d7aa1c78-0e46-11e8-8173-0f1bc8603e8b.png)

**Comment by mahestro** [comment]
The local photo operation is done through the + buttons in behind the popup. This popup is shown only once at the time the user steps on the photos section.
