### ISSUE TITLE
Website: There is no way to vie the passcode that one is creating

### ISSUE THREAD

**Issue by nithyaasworld** [topcoderinc/mjolnir-web#9]
_From @bckingsbury on January 10, 2018 20:28_

One the initial signup page there has to be either another field that one can use to verify they typed the right passcode or a way to view what one typed to verify it themselves before submitting. 

_Copied from original issue: topcoderinc/mjolnir-app#394_

**Comment by mahestro** [comment]
🤔 http://take.ms/W9HAm
