### ISSUE TITLE
Need to remove plus sign on User profile in the Users section

### ISSUE THREAD

**Issue by bckingsbury** [topcoderinc/mjolnir-web#90]
### OS and Browser Details ###
IPad Pro - iOS 11.2.2

### Screen Name where the issue occurs ###
The User section of the app
### Exact Reproduction Steps ###
1. Go to the that section
2. 

### Actual  Result ###
When the user profile is highlight and enlarged(on the far left) it has a plus sign next to it allowing the user to create another user profile. 

### Expected Result ###
There can only be one User profile so there should not be a plus sign when that profile is selected. 

The office profile should all have plus signs attached to them so that additional offices can be created. 

### Screenshots/Video ###

![119be95d-28cd-47e5-8d6e-664cef2f5aca](https://user-images.githubusercontent.com/31655780/36063318-9b8aa0fe-0e38-11e8-8164-9bf3234b59e1.jpeg)

**Comment by mahestro** [comment]
Good one. Easy fix.

**Comment by mahestro** [comment]
Fixed #97
